cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [

    path('', views.detail, name='detail'),
    path('add/<int:id>/',views.add, name='add_cart'),
    path('remove/<int:id>/',views.remove, name='remove_cart'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board import views
from item import views as item_views
from board.views import CustomPasswordChangeView
app_name='main'
urlpatterns = [
    path('admin/', admin.site.urls), #관리자 페이지
    path('', item_views.best, name='best_item'), #인덱스
    path('', views.index), #인덱스


    path('board/', include('board.urls')), #게시판
    path('item/', include('item.urls')),  # 제품페이지
    path('cart/', include('cart.urls')), #장바구니
    path('coupon/', include('coupon.urls')), #장바구니
    path('', include('common.urls')),#allauth  로
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('', include('allauth.urls')),
    path('', include('order.urls')), #장바구니



]

# 이미지 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupon/urls.py
from django.urls import path

from coupon import views

app_name = 'coupon'

urlpatterns = [

    path('add/', views.add_coupon, name='add'),

]

item/urls.py
from django.urls import path

from item import views

app_name = 'item'


urlpatterns = [

    path('', views.item_list, name='item_list'),
    path('<int:id>', views.item_detail, name='item_detail'),

    path('create/', views.item_create, name='item_create'),
    path('category/<str:slug>/', views.category_page, name='category_page'),
    path('<int:id>/like/', views.like_vote, name='like_vote'),


    ]

order/urls.py
from django.urls import path

from order import views

app_name = 'order'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('complete/', views.order_complete, name='order_complete'),
    path('create/<int:id>',views.order_form, name='order_form')

    ]

cart/models.py
from django.conf import settings

from coupon.models import Coupon
from item.models import Item

from decimal import Decimal


class Cart(object):
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_ID)
        if not cart:
            # 세션에 없던 키 값을 생성하면 자동 저장
            cart = self.session[settings.CART_ID] = {}
            # 세션에 이미 있는 키 값에 대한 값을 수정하면 수동으로 저장
        self.cart = cart
            # 쿠폰을 사용 할 수 있도록 세션에서 쿠폰 가져오기
        self.coupon_id = self.session.get('coupon_id')

    def __len__(self):
        # 요소가 몇개인지 갯수를 반환해주는 함수
        return sum(cart_item['quantity'] for cart_item in self.cart.values())


    def __iter__(self):
        # for문 같은 문법을 사용할 때 안에 있는 요소를 어떤 형태로 반환할 것인지 결정하는 함수
        Item_ids =   self.cart.keys()

        items = Item.objects.filter(id__in=Item_ids)

        for item in items:
            self.cart[str(item.id)]['item'] = item

        for cart_item in self.cart.values():
            cart_item['itme_price'] = Decimal(cart_item['item_price'])
            cart_item['total_price'] = Decimal( cart_item['item_price']) * cart_item['quantity']

            yield cart_item

    def add(self, item, quantity=1, is_update=False):
        item_id = str(item.id)
        if item_id not in self.cart:
            self.cart[item_id] = {'quantity':0, 'item_price':str(item.item_price)}
        # 만약 제품 정보가 Decimal 이라면 세션에 저장할 때는 str로 형변환 해서 저장하고
        # 꺼내올 때는 Decimal로 형변환해서 사용해야 한다.
        if is_update:
            self.cart[item_id]['quantity'] = quantity
        else:
            self.cart[item_id]['quantity'] += quantity

        self.save()

    def save(self):
        self.session[settings.CART_ID] = self.cart
        self.session.modified = True

    def remove(self, item):
        item_id = str(item.id)
        if item_id in self.cart:
            del(self.cart[item_id])
            self.save()

    def clear(self):
        self.session[settings.CART_ID] = {}
        # 장바구니를 비웠을 때 쿠폰도 삭제
        self.session['coupon_id'] = None
        self.session.modified = True

    #전체 제품 가격
    def get_product_total(self):
        return sum(Decimal(cart_item['item_price']) * cart_item['quantity'] for cart_item in self.cart.values())


    @property
    def coupon(self):
        if self.coupon_id:
            return Coupon.objects.get(id=self.coupon_id)  # 데이터 베이스에서 쿠폰 가져오기

    # 할인 금액
    def get_discount_total(self):
        if self.coupon:
            if self.get_product_total() >= self.coupon.discount:
                return self.coupon.discount
        return Decimal(0)

    # 할인 금액이 반영된 상품 금액
    def get_total_price(self):
        return self.get_product_total() - self.get_discount_total()

cart/forms.py
from django import forms


class AddItemForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from coupon.forms import AddCouponForm
from .forms import AddItemForm

from item.models import Item
from .models import Cart


@require_POST
def add(request, id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=id)

    #유효성 검사
    form = AddItemForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(item=item, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')

def remove(request, id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=id)
    cart.remove(item)
    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()
    for cart_item in cart:
        cart_item['quantity_form'] = AddItemForm(initial={'quantity': cart_item['quantity'], 'is_update': True})
    return render(request, 'cart/cart_detail.html', {'cart':cart ,'add_coupon':add_coupon})

templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
{% endblock %}

{% block content %}
<section id="wrap">
<div class="cart-form">
  <h3>장바구니</h3>
  <table class="cart-wrap table_one">
    <col style="width:200px;">
    <col style="width:400px;">
    <col style="width:150px;">
    <col style="width:200px;">
    <col style="width:100px;">
    <col style="width:200px;">
    <thead  class="thead_one">
      <tr class="tr_one">
        <th class="th_one">제품이미지</th>
        <th class="th_one">제품명</th>
        <th class="th_one">제품수량</th>
        <th class="th_one">제품삭제</th>
        <th class="th_one">제품단가</th>
        <th class="th_one">총금액</th>
      </tr>
    </thead>
    <tbody>
      {% for it in cart %}
        {% with item=it.item %}
        <tr class="tr_one">
          <!-- 제품 이미지 -->
          <td class="cart-img">
            <a href="{{ item.get_absolute_url }}">
              <img src="{{item.item_image.url }}" class="img-thumbnail">
            </a>
          </td >
          <!-- 제품명 -->
          <td>
            <a href="{{ item.item_detail.url }}">{{ item.item_title }}</a>
          </td>
          <!-- 제품 수량-->
          <td>
            <form class="" action="{% url 'cart:add_cart' item.id %}" method="post">
              {% csrf_token %}
              {{ it.quantity_form.quantity }}
              {{ it.quantity_form.is_update }}
             <button class="btn_one1 custom-btn" type="submit" >Update</button>

            </form>
          <!-- 제품 삭제 -->
          </td>
          <td><a href="{% url 'cart:remove_cart' item.id %}">
            <button class="btn_one1 custom-btn" >Remove</button></a></td>
          <!-- 제품 단가-->
          <td class="num">{{ it.item_price|intcomma }}원</td>
          <!-- 토탈 금액 -->
          <td class=""><b>{{it.total_price|intcomma}}</b>원</td>
        </tr>
        {% endwith %}
      {% endfor %}

      {% if cart.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="4"></td>
          <td>{{ cart.get_product_total|intcomma }}원</td>
        </tr>
        <tr>
          <td>"{{cart.coupon.code}}" 쿠폰 할인금액:{{ cart.coupon.discount|intcomma }}원<br></td>
          <td colspan="4"></td>
          <td>- {{ cart.get_discount_total|intcomma }}</td>
        </tr>
      {% endif %}
      <tr>
        <form action="{% url 'coupon:add' %}" method="post">
            {{add_coupon}}
            <td class="add2"><input type="submit" value="Add"></td>
            {% csrf_token %}
        </form>
      </tr>
      <!-- 총 금액 -->
      <tr class="cart-total-price" style="height: 60px;">
        <td>합계 금액</td>
        <td colspan="4"></td>
        <td class="num">총 <b>{{ cart.get_total_price|intcomma }}</b> 원</td>
      </tr>
    </tbody>
  </table>


    <div class="cart-bottom">
      <button type="button" class="cart-check">
        <a href="{% url 'order:order_create'%}" class="btn btn-primary">주문하기</a>
      </button>
    </div>
    <div class="keep-shopping">
    <a href="{% url 'item:item_list' %}">계속 쇼핑하기</a>
    </div>
</div>
  {% include 'footer.html' %}
  </section>
{% endblock %}