board/urls.py
from django.urls import path
from . import views


app_name = 'board'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'), # 질문등록
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'), # 답변등록
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'), # 질문삭제
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),  # 질문수정
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),  # 답변삭제
    path('board/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),  # 답변수정
    path('event', views.event, name='event'),  # 답변수정
    # 공지사항
    path('notice/', views.notice_list, name='notice_list'),
    path('notice/<int:notice_id>/', views.detail, name='notice_detail'),
    path('notice/create/', views.notice_create, name='notice_create'),
    path('notice/delete/<int:notice_id>/', views.notice_delete, name='notice_delete'),
    path('notice/modify/<int:notice_id>/', views.notice_modify, name='notice_modify'),

    path('service/', views.service, name='service'),

]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [

    path('', views.detail, name='detail'),
    path('add/<int:id>/',views.add, name='add_cart'),
    path('remove/<int:id>/',views.remove, name='remove_cart'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from common import views

app_name = 'common'

urlpatterns = [
    path('<int:id>/', views.detail, name='detail'),
    path('signup/', views.CustomSignupView.as_view(), name='account_signup'),
    path('membership/', views.membership, name='membership'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board import views
from item import views as item_views
from board.views import CustomPasswordChangeView
app_name='main'
urlpatterns = [
    path('admin/', admin.site.urls), #관리자 페이지
    path('', item_views.best, name='best_item'), #인덱스
    path('', views.index), #인덱스


    path('board/', include('board.urls')), #게시판
    path('item/', include('item.urls')),  # 제품페이지
    path('cart/', include('cart.urls')), #장바구니
    path('coupon/', include('coupon.urls')), #장바구니
    path('', include('common.urls')),#allauth  로
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('', include('allauth.urls')),
    path('', include('order.urls')), #장바구니



]

# 이미지 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from item import views

app_name = 'item'


urlpatterns = [

    path('', views.item_list, name='item_list'),
    path('<int:id>', views.item_detail, name='item_detail'),

    path('create/', views.item_create, name='item_create'),
    path('category/<str:slug>/', views.category_page, name='category_page'),
    path('<int:id>/like/', views.like_vote, name='like_vote'),


    ]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styleY.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="https://kit.fontawesome.com/cf70e4dc4a.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="{% static 'js/login.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">
</head>
<body>
{% include 'header.html' %}
{% block script %}
{% endblock %}

{% include 'navbar.html' %}
<!--    본문 내용 start-->
{% block content %}

{% endblock %}

<!--본문 내용 end-->

<!-- 제이쿼리 영역 -->
</body>

</html>

templates/footer.html
{% load static%}
<footer class="footer">

    <section id="top">

        <ul class="flex">
            <li class="footer info">
                <h2 class="text-lg uppercase">Customer Service</h2>
                <span class="number-info block text-lg">070 - 0123 - 0123<br></span>
                <span class="time-info block">평일 | 11:00 ~ 16:00<br/><span class="lunch">(점심시간 13:00~14:00)</span></span>
                <span class="closed-info block">주말 및 공휴일 휴무</span>
            </li>
            <li class="vertical-line"></li>
            <li class="xans-layout-footer csInfo">
                <h2 class="text-lg uppercase">Offline Store</h2>
                <span class="number-info text-lg block">070 - 0123 - 0123<br></span>
                <span class="time-info block">평일 &amp; 주말 | 12:00 ~ 20:30</span>
                <span class="closed-info block">월요일 휴무</span>
            </li>
            <li class="vertical-line"></li>
            <li class="accInfo">
				<h2 class="text-lg uppercase">Account</h2>
				<span class="number-info text-lg block">078 - 123456 - 01 - 012<br></span>
				<span class="time-info block">기업은행 (주)두샤</span>
			</li>
            <li class="vertical-line"></li>
            <li class="partnershipInfo">
				<h2 class="text-lg uppercase">Partnership</h2>
				<span class="number-info text-lg block">070 - 0123 - 1234<br></span>
				<span class="time-info block ">입점 및 제휴문의</span>
                <span class="time-info block">project_team@dusha.com</span>
			</li>
        </ul>
    </section>
    <section id="footer-bottom">
        <h2>DUSHA PROCESS</h2>
        <span>국가기관에 정식 등록된 공식 수입사,두샤의 모든 제품은 국문 라벨이 부착된
                100% 정품임을 보증합니다.<br>
        </span>
        <!--<ul class="service">
            <li><a href="#" class="service1">회사소개 |</a></li>
            <li><a href="#" class="service2">이용약관 |</a></li>
            <li><a href="#" class="service3">개인정보처리방침 |</a></li>
            <li><a href="#" class="service4">이용안내</a></li>
        </ul>-->
        <ul>
            <li class="follow">
                    <i class="fa-brands fa-instagram"></i>
                    <i class="fa-brands fa-facebook"></i>
                    <i class="fa-brands fa-twitter"></i>
            </li>
        </ul>
        <ul>
            <li>
               <span>상호명 | </span>
               주식회사 dusha
            </li>
            <li>
               <span>대표자 | </span>
               향수조아
            </li>
            <li>
               <span>사업자등록번호 | </span>
               654-33-00156
            </li>
            <li>
               <span>통신판매업신고번호 | </span>
               제 2023-서울종로-0627 호
            </li>
            <li>
               <span>고객센터 | </span>
               02-3481-1005
            </li>
            <li>
               <span>주소 | </span>
               서울 강남구 테헤란로5길 24 장연빌딩 3~7층
            </li>
            <li>
                <span>개인정보보호책임자 | </span>
                두샤(dusha)
            </li>
            <li class="copy ">Copyright © 두샤. All rights reserved.</li>
        </ul>
    </section>


</footer>

templates/form_errors.html
<!--유효성 검사 - 오류 처리 시작-->
{% if form.errors %}
    <!-- 필드 오류 -->
    {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger" style="color: red; font-size: 0.6em;">
            <strong>{{ field.label }}</strong>
            {{ error }}
          </div>
        {% endfor %}
    {% endfor %}
    <!-- 넌 필드 오류 -->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger" style="color: red;">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/header.html
{% load static %}
<header>
    <div class="header_wrap">

        <div class="header_index">
            <div class="logo">
                <a href="/">
                    <img src="/static/images/logo.png">
                </a>
            </div>
            <div class="gnb">
                <ul class="nav_intro">

                    {% if user.is_authenticated %}
                    <li><a href="{% url 'account_logout' %}">Logout</a></li>
                    <li><a href="{% url 'common:detail' user.id %}">회원정보</a></li>
                    <li><a href="{% url 'cart:detail'%}">CART</a></li>
                    {%else%}
                    <li><a href="{% url 'account_login' %}">LOGIN</a></li>
                    <li><a href="{% url 'cart:detail'%}">CART</a></li>
                    <li><a href="{% url 'account_signup' %}">SIGNUP</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </div>


</header>

templates/navbar.html
<aside class="side-bar" style="z-index: 999;">

  <ul>
    <li>
      <a href="{% url 'item:item_list' %}">All</a>

    </li>
    <li>
      <a href="">PERFUME</a>
      <ul>

        <li><a href="{% url 'item:category_page' '조말론' %}">Jo Malone</a></li>
        <li><a href="{% url 'item:category_page' '딥디크' %}">DIPTYQUE</a></li>
        <li><a href="{% url 'item:category_page' '디올' %}">DIOR</a></li>
        <li><a href="{% url 'item:category_page' '바이레도' %}">BYREDO</a></li>

      </ul>
    </li>
    <li>
      <a href="#">DEFUSER</a>
      <ul>

        <li><a href="{% url 'item:category_page' '조말론-디퓨져' %}">Jo Malone</a></li>
        <li><a href="{% url 'item:category_page' '코코도로-디퓨져 ' %}">COCODOR</a></li>
        <li><a href="{% url 'item:category_page' '딥디크-디퓨져' %}">DIPTYQUE</a></li>

      </ul>
    </li>
    <li><a href="{% url 'board:event' %}">EVENT</a></li>
    <li><a href="{% url 'board:notice_list' %}">NOTICE</a></li>
    <li><a href="{% url 'board:question_list' %}">QNA</a></li>
    <li><a href="{% url 'common:membership' %}">MEMBERSHIP</a></li>
  </ul>
</aside>