board/urls.py
from django.urls import path
from . import views


app_name = 'board'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'), # 질문등록
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'), # 답변등록
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'), # 질문삭제
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),  # 질문수정
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),  # 답변삭제
    path('board/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),  # 답변수정
    path('event', views.event, name='event'),  # 답변수정
    # 공지사항
    path('notice/', views.notice_list, name='notice_list'),
    path('notice/<int:notice_id>/', views.detail, name='notice_detail'),
    path('notice/create/', views.notice_create, name='notice_create'),
    path('notice/delete/<int:notice_id>/', views.notice_delete, name='notice_delete'),
    path('notice/modify/<int:notice_id>/', views.notice_modify, name='notice_modify'),

    path('service/', views.service, name='service'),

]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [

    path('', views.detail, name='detail'),
    path('add/<int:id>/',views.add, name='add_cart'),
    path('remove/<int:id>/',views.remove, name='remove_cart'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board import views
from item import views as item_views
from board.views import CustomPasswordChangeView
app_name='main'
urlpatterns = [
    path('admin/', admin.site.urls), #관리자 페이지
    path('', item_views.best, name='best_item'), #인덱스
    path('', views.index), #인덱스


    path('board/', include('board.urls')), #게시판
    path('item/', include('item.urls')),  # 제품페이지
    path('cart/', include('cart.urls')), #장바구니
    path('coupon/', include('coupon.urls')), #장바구니
    path('', include('common.urls')),#allauth  로
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('', include('allauth.urls')),
    path('', include('order.urls')), #장바구니



]

# 이미지 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from item import views

app_name = 'item'


urlpatterns = [

    path('', views.item_list, name='item_list'),
    path('<int:id>', views.item_detail, name='item_detail'),

    path('create/', views.item_create, name='item_create'),
    path('category/<str:slug>/', views.category_page, name='category_page'),
    path('<int:id>/like/', views.like_vote, name='like_vote'),


    ]

board/models.py
from django.db import models
from common.models import User
from item.models import Item


# 질문 모듈(q&n)
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject
# 답변 모듈(q&n)
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content
# 공지사항 모듈(q&n)

class Notice(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    photo = models.ImageField(blank=True)
    file = models.FileField(blank=True)
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

board/forms.py
from django import forms
from board.models import Question, Answer, Notice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변 내용'
        }
class NoticeForm(forms.ModelForm):
    class Meta:
        model =Notice
        fields = ['subject', 'content', 'file','photo']
        labels = {
            'subject' : '제목',
            'content' : '내용',
            'file' : '파일',
            'photo' : '포토'
        }

board/views.py
from allauth.account.views import  PasswordChangeView
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from board.models import Question, Answer, Notice
from board.forms import QuestionForm, AnswerForm, NoticeForm
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q


def index(request):
    print(request.user)
    return render(request, "board/index.html")

def event(request):

        return render(request, "board/event.html")

#비밀번호 변경시 인덱스 페이지로 리버스
class CustomPasswordChangeView(PasswordChangeView):
    def get_success_url(self):
        return reverse('index')

#질문 목록
def question_list(request):
    #question_list = Question.objects.all()
    page =request.GET.get('page', 1)
    kw = request.GET.get('kw', '')

    question_list = Question.objects.order_by('-create_date')
    if  kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains =kw)|
            Q(answer__content__icontains=kw)).distinct()

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 설정
    page_obj = paginator.get_page(page)  # 페이지 가져오기
    context = {'question_list': page_obj, 'page': page, 'kw': kw}

    return render(request, 'board/question_list.html', context)


def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id) # 데이터가 없으면 404 처리
    context = {'question' : question}
    return render(request, 'board/detail.html', context)

# 질문 등록
@login_required(login_url='/login/') # 로그인 페이지로 이동
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST) # 입력된 데이터가 있는 폼
        if form.is_valid(): # 폼이 유효성 검사를 통과했다면
            question = form.save(commit=False) #가저장
            question.author = request.user # 세션 권한(로그인한) 있는 글쓴이
            question.create_date = timezone.now()  #등록일 생성
            form.save() #진짜로 저장
            return redirect('board:question_list') # 질문 목록 페이지 이동

    else:  #get 방식
        form = QuestionForm()  #폼 객체 생성(빈 폼 생성)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)  # get 방식

# 답변 등록
@login_required(login_url='/login/')
def answer_create(request, question_id):

    # question = Question.objects.get(id=question_id) #해당 id의 질문 객체 생성
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)  # 입력값 전달받음
        if form.is_valid():
            answer = form.save(commit=False)  # 내용만 저장됨
            answer.create_date = timezone.now()  # 작성일
            answer.author = request.user  # 세션 발급
            answer.question = question  # 외래키 질문 저장
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'board/detail.html', context)


# 질문수정
@login_required(login_url='/login/')
def question_modify(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)


# 질문 삭제
@login_required(login_url='/login/')
def question_delete(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('board:question_list')


# 답변 삭제
@login_required(login_url='/login/')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()

# 답변 수정
@login_required(login_url='/login/')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('board:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'board/answer_form.html', context)

#공지사항

def notice_list(request):
    #question_list = Question.objects.all()
    page =request.GET.get('page', 1)
    kw = request.GET.get('kw', '')

    notice_list = Notice.objects.order_by('-create_date')
    if  kw:
        notice_list = notice_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw)).distinct()

    paginator = Paginator(notice_list, 10)  # 페이지당 10개씩 설정
    page_obj = paginator.get_page(page)  # 페이지 가져오기
    context = {'notice_list': page_obj, 'page': page, 'kw': kw}

    return render(request, 'board/notice_list.html', context)


def notice_detail(request, notice_id):
    #question = Question.objects.get(id=question_id)
    notice = get_object_or_404(Notice, id=notice_id) # 데이터가 없으면 404 처리
    context = {'notice' : notice}
    return render(request, 'board/notice_detail.html', context)


# 질문 등록
def is_admin(user):
    return user.is_superuser or user.username == '123'

@user_passes_test(is_admin)
def notice_create(request):
    if request.method == "POST":
        form = NoticeForm(request.POST) # 입력된 데이터가 있는 폼
        if form.is_valid(): # 폼이 유효성 검사를 통과했다면
            notice = form.save(commit=False) #가저장
            notice.author = request.user # 세션 권한(로그인한) 있는 글쓴이
            notice.create_date = timezone.now()  #등록일 생성
            form.save() #진짜로 저장
            return redirect('board:notice_list') # 질문 목록 페이지 이동

    else:  #get 방식
        form = NoticeForm()  #폼 객체 생성(빈 폼 생성)
    context = {'form': form}
    return render(request, 'board/notice_form.html', context)  # get 방식

# 공지사항수정
@login_required(login_url='/login/')
def notice_modify(request, notice_id):

    notice = get_object_or_404(Notice, pk=notice_id)
    if request.method == "POST":
        form = NoticeForm(request.POST, instance=notice)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.author = request.user
            notice.modify_date = timezone.now()
            notice.save()
            return redirect('board:detail', notice_id=notice.id)
    else:
        form = NoticeForm(instance=notice)
    context = {'form': form}
    return render(request, 'board/notice_form.html', context)


# 질문 삭제
@login_required(login_url='/login/')
def notice_delete(request, notice_id):

    notice = get_object_or_404(Notice, pk=notice_id)
    notice.delete()
    return redirect('board:notice_list')




def service(request):
    return render(request, "board/service.html")

templates/board/detail.html
{% extends 'base.html' %}
{% block content %}


<div id="wrap">
    <section id="detail">
        <!-- 질문 전체 섹션-->
        <div class="board-detail">
            <!-- 질문 제목 -->
            <h2 class="board-detail-title">
                제목 : {{ question.subject }}
            </h2>
                <div class="board-detail-content">
                    <div class="card-body">
                        <!-- 줄바꿈 style="white-space: pre-line"-->
                        <!-- 질문 내용 -->
                        <div class="card-text">
                            {{ question.content }}
                        </div>
                        <!-- 글쓴이, 작성시간 -->
                        <div class="card-writer-time">
                            <div class="card-writer">
                                <b>작성자</b> |  {{ question.author }}
                            </div>
                            <div class="card-time">
                                <b>작성일</b> |  {{ question.create_date }}
                            </div>
                        </div>
                    </div>
                        <!-- 글쓴이가 로그인한 사람과 일치하면 -->
                        {% if question.author == request.user %}
                        <div>
                            <a href="{% url 'board:question_modify' question.id %}">수정</a>
                            <a href="#"
                               data-uri="{% url 'board:question_delete' question.id %}">삭제</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div>
                    <h5>{{ question.answer_set.count }} 개의 답변이 있습니다.</h5>
                </div>
            {% for answer in question.answer_set.all %}
            <div class="answer-detail">
                <div class="card-body">
                    <div class="card-text">
                        {{ answer.content }}    <!-- 답변 내용 -->
                    </div>
                    <div class="card-answer-time">
                        <div class="answer-writer">
                            <b>작성자</b> |  {{ question.author }}
                        </div>
                        <div class="answer-time">
                             <b>작성일</b> |  {{ question.create_date }}
                        </div>
                    </div>
                    <!-- 글쓴이가 로그인한 사람과 일치하면 -->
                    {% if answer.author == request.user %}
                    <div class="answer-modify-delete">
                        <a href="{% url 'board:answer_modify' answer.id %}">
                            <button type="submit" class="custom-btn btn_one1">수정</button></a>
                        <a href="#"
                           data-uri="{% url 'board:answer_delete' answer.id %}">
                            <button type="submit" class="custom-btn btn_one1">삭제</button></a>
                    </div>
                    {% endif %}
                </div>
        </div>

        {% endfor %}

        <!-- 답변 등록 폼 -->
        <form action="{% url 'board:answer_create' question.id %}"
                        method="post">
            {% csrf_token %} <!-- 필수 : 403 권한 데러 발생 -->
            {% include 'form_errors.html' %}
            <div class="form-group">
                <textarea name="content" rows="10"
                          cols="50" class="form-control mb-3"
                    {% if not user.is_authenticated %}disabled{% endif %}></textarea>
            </div>
            <button type="submit" class="custom-btn btn_one1">답변 등록</button>
        </form>
    </section>
    {% include 'footer.html' %}
</div>




{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('.delete').click(function(){  // 삭제 버튼을 클릭하면
            if(confirm('정말 삭제하시겠습니까?')){
                location.href=$(this).data('uri');  // 현재 대상 객체의 주소를 이동
            }
        });
    });
</script>
{% endblock %}

templates/board/event.html
{% extends 'base.html' %}
{% block content %}

{% load static %}


{% include 'header.html' %}
{% include 'navbar.html' %}


<section id="wrap">
<div class="event"><h1> DUSHA 이벤트</h1></div>

<!-- Wrap the slider in div with overflow hidden to hide scrollbars -->
<div class="overflow-hidden">

  <!-- The slider itself is a flex grid -->
  <div class="flex -mx-4 img-ticker">

    <!-- Original set of images -->
    <!-- Each image is a grid column with width 16rem (w-64) and horiztonal margin 1rem (mx-4) -->
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event1.jpg'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event2.png'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event3.jpg'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event4.jpg'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event5.png'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event6.jpg'%}">

    <!-- Copy set of images -->
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event1.jpg'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event2.png'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event3.jpg'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event4.jpg'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event5.png'%}">
    <img class="w-64 mx-4 self-start flex-none" src="{% static 'images/event6.jpg'%}">
  </div>
</div>
{% include 'footer.html' %}
</section>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% load static %}{% load humanize %}
{% block content %}
{% block scripts%}
<script>
 {% if messages %}
        {% for message in messages %}
            alert("{{ message }}");
        {% endfor %}
    {% endif %}

</script>
{%endblock%}
<p id="intro_text" class="flashing">DUSHA even makes your soul smell good.</p>
  <video src="{% static '/video/bg.mp4' %}" autoplay muted loop></video>

<section id="container" >
<section id="wrap" >
 </section>
    <section id="c">
        <ul class="amount">
            <li>
                <div>
                    <div class="contents1">SPECIAL GIFT EVENT</div>
                    <div class="result">딥디크 브랜드 파우치 증정</div>
                </div>
            </li>
            <li>
                <div>
                    <div class="contents1">커스텀 선물 포장 패키지</div>
                    <div class="result">직접고르는 선물포장 서비스</div>
                </div>
            </li>
            <li>
                <div>
                    <div class="contents1">New Brand Free Gift Event</div>
                    <div class="result">바디워시 샘플 3종 증정</div>
                </div>
            </li>
            <li>
                <div>
                    <div class="contents1">감도를 채워줄 나만의 향수</div>
                    <div class="result">1:1 맞춤 추천</div>
                </div>
            </li>
        </ul>
    </section>

    <section id="d">
        <div class="main_text0">
            <h1>DUSHA</h1>
            <div class="contents1">향을 찾아드리고 전달 드리는 모든 과정 속에서<br>
                ‘제품 구매’ 그 이상의 경험을 느끼실 수 있도록,
                퍼퓸그라피가 고객님만을 위한 향수 전문가가 되어드리겠습니다.
            </div>

            <ul class="icons">
                <li>
                    <div class="icon_img">
                        <img src="static/images/social-care.png">
                    </div>
                    <div class="contents1_bold"><100% 직수입, 본사 검수></div>
                    <div class="contents2">
                        국가 기관에 정식으로 등록된 향수 전문 셀렉트샵으로,
                        오직 정품만 취급하고 정식품질관리를 통해
                        엄격한 품질관리를 유지하고 있습니다
                    </div>
                    <div class="ex1">
                        <img src="static/images/01.png">
                    </div>
                    <!--                <div class="more">
                                        MORE
                                    </div>-->
                </li>

                <li>
                    <div class="icon_img">
                        <img src="static/images/like.png">
                    </div>
                    <div class="contents1_bold">
                        <p>
                            향기에 깊이를 더해주는 시향 컨텐츠
                        </p>
                    </div>
                    <div class="contents2">
                        향수 맞춤 추천, 시각적 이미지 등 향기에 대한 더욱 섬세하고 전문적인 인사이트까지
                        제공하며 향기에 깊이를 더해드릴 수 있도록 도움을 드리고 있습니다.
                    </div>
                    <div class="ex2">
                        <img src="static/images/02.png">
                    </div>
                    <!--                <div class="more">
                                        MORE
                                    </div>-->
                </li>

                <li>
                    <div class="icon_img">
                        <img src="static/images/truck.png">
                    </div>
                    <div class="contents1_bold">
                        꼼꼼하고 안전한 포장, 당일 발송
                    </div>
                    <div class="contents2">
                        두샤에서만 제공하는 커스텀 선물 포장으로 고객님드르이 소중한 마음까지 전달될 수 있도록 노력하고 있습니다.
                        또한, 14시 이전 주문 건은 모두 당일 출고해드리고 있습니다.
                    </div>
                    <div class="ex3">
                        <img src="static/images/03.png">
                    </div>
                    <!--                <div class="more">
                                        MORE
                                    </div>-->
                </li>
            </ul>
        </div>
    </section>

<section id="g">
    <section id="best_item2">
        <div class="bi_title">
            <h3 id="bi_text1">BEST & HOT</h3>
            <h2 id="bi_text">가장 주목받는 베스트 향수</h2>
        </div>
        <!-- 1 -->
        <section id="bi_detail">
            <div class="slider">
             {% for item in best_list %}
            <div class="bs1">
                 <div class="item-title">{{item.item_title}}</div>
                <div class="shine">
                <a href="{% url 'item:item_detail' item.id %}" > <figure><img src="{{item.item_image.url}}" alt="베스트 상품" width="300" height="300"></figure></a>
                 </div>
                    <div class="item-subtitle color-8D">{{item.content}}</div>
                <div>{{item.item_price|intcomma}}원</div>
            </div>
                    {% endfor %}
            </div>

        </section>
 </section>

    <section id="4">
        <div class="main_text1">
            <h1>OUR SERVICE</h1>
            <div class="contents1">
                온라인 샵에서 제공하는 제품들을 백화점과는 달리<br>
                매우 자유로운 분위기 속에서 마음껏 시향하실 수 있는
                오프라인 스토어를 운영 중이며, <br>
                직원들의 전문적인 취향 맞춤 추천서비스를<br>
                받아 보실 수 있는 공간입니다.
            </div>
            <div class="service">
                <div class="S_photo">
                    <img src="static/images/04.png">
                </div>
                <div class="contents2">
                    <h2>OUR VISION</h2>
                    고객님들의 목소리를 귀담아 들으며
                    ‘제품 구매’ 그 이상의 경험을 제공해드리기 위해 끊임없이 고민하고 있습니다.<br>
                    고객님들이 원하시는 향기를 마음껏 즐기실 수 있게, 더 나아가 향기에 깊이를 더할 수 있도록<br>
                    퍼퓸그라피가 고객님들에게 다가가겠습니다.
                </div>
            </div>
        </div>

        <div class="main_text2">
            <ul>
                <li>
                    <div><h1>DUSHA</h1></div>
                    <div>DUSHA even makes your soul smell good.</div>
                    <div class="more2">더 알아보기</div>
                </li>
                <li></li>
            </ul>
        </div>


    </section>

    <section id="5"></section>
    </section>
{% include 'footer.html' %}

</section>
<!--<div class="top"><a>NEW프래그런스 시트러스 컬렉션</a></div>&ndash;&gt;-->


<!-- intro end -->

<!-- amount end -->


{% endblock %}

{% include 'footer.html' %}

templates/board/notice_detail.html
{% extends 'base.html' %}
{% block content %}
{% if not user_passes_test %}
    <script>
        alert("관리자만 접근할 수 있습니다.");
         </script>
{% endif %}

<section id="wrap">
    <section id="detail">

        <h2 class="border-bottom py-2">{{ notice.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <!-- 줄바꿈 style="white-space: pre-line"-->
                <div class="card-text" style="white-space: pre-line">
                    {{ notice.content }}  <!-- 질문 내용 -->
                    {{ notice.file }}  <!-- 질문 내용 -->
                    <img src=" {{ notice.photo }}">  <!-- 질문 내용 -->
                </div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-info text-start">
                        <div class="mb-2">{{ notice.author }}</div>
                        <div>{{ notice.create_date }}</div>
                    </div>
                </div>


            </div>
        </div>



            </div>
        </div>



    </section>
    {% include 'footer.html' %}
</section>




{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('.delete').click(function(){  // 삭제 버튼을 클릭하면
            if(confirm('정말 삭제하시겠습니까?')){
                location.href=$(this).data('uri');  // 현재 대상 객체의 주소를 이동
            }
        });
    });
</script>
{% endblock %}

templates/board/notice_list.html
{% extends 'base.html' %}
{% block content %}

<section id="wrap">

<div class="question-list">

<h2>공지사항</h2>
    <table class="table_one">
        <col style="width:100px;">
        <col style="width:400px;">
        <col style="width:400px;">
        <col style="width:150px;">
        <thead class="thead_one">
            <tr class="tr_one">
                <th class="tr_one">번호</th>
                <th class="tr_one">제목</th>
                <th class="tr_one">작성일</th>
                <th class="tr_one">작성자</th>
            </tr>
        </thead>
        <tbody class="thead_one">
            {% if notice_list %}
                {% for notice in notice_list %}
                <tr class="tr_one">
                    <!-- 글 번호 -->
                    <td class="td_one">
                        {{ forloop.counter }}
                    </td>
                    <!-- 글 제목-->
                    <td class="td_one">
                        <a href="{% url 'board:notice_detail' notice.id %}">{{ notice.subject }}</a>
                    </td>
                    <!-- 글 작성일 -->
                    <td class="td_one">{{ notice.create_date }}</td>
                    <!-- 작성자 -->
                    <td class="td_one">{{ notice.author }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr class="tr_one">
                    <td class="td_one" colspan="4" >공지가  없습니다.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>

    <!--질문 등록 버튼 -->
    <div class=" frame">
        <button type="submit" class="custom-btn btn_one1 create-button" >
            <a href="{% url 'board:notice_create' %}">공지 등록</a>
        </button>
    </div>

        <!--페이징 처리 시작  -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if notice_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ notice_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in notice_list.paginator.page_range %}
        {% if page_number >= notice_list.number|add:-5 and page_number <= notice_list.number|add:5 %}
        {% if page_number == notice_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if notice_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ notice_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
<!--    검색창 -->

        <form action="" method="get" id="searchForm"> <!-- page, kw get방식으로 요청 -->
            <input type="hidden" name="kw" id="kw">
            <input type="hidden" name="page" id="page">
        </form>

  <!--검색 입력 상자와 찾기버튼-->
    <div class="search">
        <div class="col-4 input-group">
            <input type="text" class="kw form-control" value="{{ kw|default_if_none:'' }}">
             <button type="button" id="btn_search"
                        class="custom-btn btn_one1">찾기</button>

        </div>
    </div>

</div>
{% include 'footer.html' %}

    </section>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        //페이지 처리
        $(".page-link").on('click', function(){   //페이지 번호를 클릭하면
            $("#page").val($(this).data("page")); //해당 페이지 번호를 page 필드에 가져옴
            $("#searchForm").submit();            //폼을 전송
        });

        //검색 처리
        $("#btn_search").on('click', function(){
           let text = $(".kw").val();          //검색어 값
           $("#kw").val(text);                 //폼의 kw 필드에 설정
           $("#page").val(1);                  //1페이지를 page 필드에 설정
           $("#searchForm").submit();          //폼을 전송
        });
    });

    $(document).ready(function() {
        $(".create-button").on("click", function(event) {
            event.preventDefault();  // 기본 동작(링크 이동)을 중지합니다.
            alert("관리자만 글을 작성할 수 있습니다.");
            // 또는 다른 알림창 스타일을 사용하려면, 대화 상자 라이브러리를 사용할 수도 있습니다.
        });
    });
</script>
{% endblock %}