cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [

    path('', views.detail, name='detail'),
    path('add/<int:id>/',views.add, name='add_cart'),
    path('remove/<int:id>/',views.remove, name='remove_cart'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board import views
from item import views as item_views
from board.views import CustomPasswordChangeView
app_name='main'
urlpatterns = [
    path('admin/', admin.site.urls), #관리자 페이지
    path('', item_views.best, name='best_item'), #인덱스
    path('', views.index), #인덱스


    path('board/', include('board.urls')), #게시판
    path('item/', include('item.urls')),  # 제품페이지
    path('cart/', include('cart.urls')), #장바구니
    path('coupon/', include('coupon.urls')), #장바구니
    path('', include('common.urls')),#allauth  로
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('', include('allauth.urls')),
    path('', include('order.urls')), #장바구니



]

# 이미지 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from item import views

app_name = 'item'


urlpatterns = [

    path('', views.item_list, name='item_list'),
    path('<int:id>', views.item_detail, name='item_detail'),

    path('create/', views.item_create, name='item_create'),
    path('category/<str:slug>/', views.category_page, name='category_page'),
    path('<int:id>/like/', views.like_vote, name='like_vote'),


    ]

item/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models

from django.urls import reverse

from config import settings


# 카테고리 모델
class Category(models.Model):
    # unique=True 중복 불허
    name = models.CharField(max_length=50, unique=True, db_index=True)
    # url주소 - 문자, allow_unicode - 한글허용
    slug = models.SlugField(max_length=200, unique=True,
                            allow_unicode=True, db_index=True)

    def __str__(self):
        return self.name

    # 카테고리 url 주소
    def get_absolute_url(self):

        return reverse('item:category_page', args=[self.slug])

    # 관리자 페이지에서 적용 - verbose_name_plural(복수형)
    class Meta:
        ordering = ['name']  # 이름순 정렬
        verbose_name = 'category'
        verbose_name_plural = 'categories'



class Item(models.Model):
    # 상품 번호, 상품명, 상품가격, 카테고리번호, 출시일, 판매량, 상품사진 , 총재고량

    GENDER_CHOICES = (
        ('MEN', 'MEN'),
        ('WOMEN', 'WOMEN'),
    )
    id = models.AutoField(primary_key=True, db_index=True)
    item_category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    item_title = models.CharField(max_length=100, unique=False)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default=1)
    content = models.TextField()
    item_price = models.IntegerField()
    # 아이템 카테고리에 속한 상품이 존재하면 카테고리 삭제 불가
    # 재고가 있으면 false 재고가 없으면 true
    soldout = models.BooleanField(default=False)
    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)
    item_likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='item_likes', blank=True)
    item_image = models.ImageField(upload_to="item/item_img/%Y/%m/%d") #제품 메인사진
    sales = models.IntegerField(default=0) #판매량
    item_content = models.ImageField(upload_to='item/item_content/%Y/%m/%d') #제품 상세 사진
    amount = models.IntegerField(default=0)
    def __str__(self):
        return self.item_title

    def category_name(self):
        return self.item_category

    def get_absolute_url(self):
        return reverse('item:item_detail', args=[self.id])

    class Meta:
        ordering = ['-create_date', 'id']  # 작성일순 정렬
        index_together = [['id']]

item/forms.py
from django import forms

from item.models import Item

#아이템 폼 생성
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item #아이템 객체 생성
        fields = ['item_title', 'content', 'item_price', 'item_image']

item/views.py
import itertools

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from cart.forms import AddItemForm
from item.forms import ItemForm
from item.models import Category, Item



# Create your views here.


#남녀 베스트 리스트
def best(request):
    #각 카테고리에서 판매량 1순위인 상품 리스트에 추가


    category = Category.objects.order_by('id').all()
    count = range(1, len(category)+1)
    best_list = Item.objects.filter(gender__isnull=True)

    for n in count:
        best = Item.objects.filter(gender='MEN',  item_category=n).order_by('-sales')[:1]
        best2 = Item.objects.filter(gender='WOMEN', item_category=n).order_by('-sales')[:1]
        best_list = itertools.chain(best, best2, best_list)

    context= {'best_list': best_list}
    return render( request, 'board/index.html',  context )

#상품 등록
def item_create(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.Files) #일반속성, 파일
        if form.is_valid(): #폼이 유효하다면
            item =form.save(commit=False) #가저장
            item.author = request.user
            item.create_date = timezone.now()
            item.save() #db에 저장
            return redirect('item:item_list')
    else:
        form = ItemForm()
    context = {'form': form}
    return render(request, 'item/item_form.html', context)

#상품 목록

def item_list(request):
    page = request.GET.get('page', 1) #페이징 처리
    kw = request.GET.get('kw', '') #검색어 가져오기
    item_list = Item.objects.order_by('-create_date') #작성일 내림차수


    if kw:
        item_list = item_list.filter(
            Q(item_title__icontains=kw) | #제목검색
            Q(content__icontains=kw)  # 내용검색

        ).distinct()
    paginator = Paginator(item_list, 12) #페이지당 10개씩 설정
    page_obj = paginator.get_page(page) #페이지 가져오기


    context = {'item_list': page_obj , 'page':page, 'kw':kw }
    return render(request, 'item/item_list.html', context)

# 카테고리 페이지
def category_page(request, slug):
    current_category = Category.objects.get(slug=slug)
    current_category = get_object_or_404(Category, slug=slug)
    item_list = Item.objects.filter(item_category=current_category) #현재 카테고리의 포스트
    item_list = item_list.order_by('-create_date')  #날짜순 내림 차순
    categories = Category.objects.all()

    context = {
        'current_category': current_category,
        'item_list': item_list,
        'categories': categories
    }
    return render(request, 'item/item_list.html', context)

def item_detail(request, id):

    item = get_object_or_404(Item, pk=id)

    add_to_cart = AddItemForm(initial={'quantity': 1})

    context = {'item': item, 'add_to_cart': add_to_cart
              }
    return render(request, 'item/item_detail.html', context)


@login_required(login_url=reverse_lazy('account_login'))
def like_vote(request, id):
    item_like = get_object_or_404(Item, pk=id)

    if request.user in item_like.item_likes.all():
        item_like.item_likes.remove(request.user)
    else:
        item_like.item_likes.add(request.user)
    item_like.save()
    return redirect('item:item_detail', id)

templates/item/index_item.html
{% load humanize %}
{% load static %}
{% block content %}
<section>
<div>
<div>
    {% for item in best_list %}
    <div>
      <!-- 배스트 상품 이미지 -->

      <div>
        <!-- 상품명-->
        <div>{{item.item_title}}</div>
          <div >
        <a href="#">
          <img src="{{item.item_image.url}}" alt="상품이미지" width="300px" >
        </a>
      </div>
        <!-- 상품상세 내용 -->
        <div>{{item.content}}</div>
        <!-- 가격 -->
        <div>{{item.item_price|intcomma}}원</div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
    {% include 'footer.html' %}
</section>
{% endblock %}

templates/item/item_admin.html
{% extends 'base.html' %
<h1> COMMING SOON </h1>

templates/item/item_detail.html
{% extends 'base.html' %}{% load humanize %}
{% load static %}
{% block content %}
<section id="wrap">

    <!-- 썸네일 + 주문창 -->
    <div class="top-info">
        <!-- 제품 이미지 -->
        <div class="thumb-img shine">
            <a href="">
                <figure class="fiimg"><img src="{{item.item_image.url}}" alt="썸네일 이미지"/>
                </figure>
            </a>
        </div>
        <!-- 주문창 -->
        <div id="item_i">
            <div class="item_info1">
                <h2>{{ item.item_title }}</h2>
                <colgroup>
                    <col style="width:500px;">
                    <col>
                </colgroup>
                <table class="item_detail_table">
                    <tbody>
                    <tr>
                        <th class="th_abc">제품 정보</th>
                        <td class="abc">{{ item.content }}</td>
                    </tr>
                    <tr>
                        <th class="th_abc">제품 가격</th>
                        <td class="price abc"><b>{{ item.item_price|intcomma }}원</b></td>
                    </tr>
                    <br>
                    <tr>
                        <th class="th_abc">배송비</th>
                        <td class="abc">2,500원(97,000원 이상 구매시 무료)</td>
                    </tr>
                    <tr>
                        <th class="th_abc">출고예정일</th>
                        <td class="abc">2시 이전 당일출고(주말, 공휴일 제외)</td>
                    </tr>
                    <tr>
                        <th class="th_abc">배송방법</th>
                        <td class="abc"> 두샤(dusha) / 본사 검수 및 직배송 / CJ대한통운</td>
                    </tr>
                    <tr>
                        <th class="th_abc">결제 가격</th>
                        <td class="abc"></td>
                    </tr>
                    </tbody>
                </table>


                <form action="{% url 'cart:add_cart' item.id %}" method="post">
                    {{ add_to_cart }}
                    {% csrf_token %}
                    <button type="submit" class="btn_one1 custom-btn">장바구니</button>

                </form>
                <div class="keep-shopping">
                    <a href="{% url 'item:item_list' %}">
                        <button type="submit" class="btn_one1 custom-btn">계속 쇼핑하기

                    </button></a></div>
            </div>

        </div>


        <!-- 상세 이미지 -->
        <div class="middle-info">
            <hr>
            <p>< 제품 상세정보 ></p>

            <a href="">
                <img class="item_conentimg" src="{{ item.item_content.url}}" alt="이미지 상세 보기"/>
            </a>
        </div>
    </div>
    <!-- 버튼 -->




    {% include 'footer.html' %}
</section>

{% endblock %}

{% block script %}

{% endblock %}

templates/item/item_form.html
{% extends 'base.html'%}
{% block content%}

<div class="container">
    <h1> 글쓰기</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">저장하기</button>


    </form>




</div>
{% endblock%}

templates/item/item_list.html
{% extends 'base.html' %}{% load humanize %}
{% load static %}
{% block content %}
<section id="wrap">
    <div class="container my-3">
        <!-- 장바구니 담음 수 -->
        <div class="cart">
            <a href="{% url 'cart:detail'%}">Cart</a>
            {% if cart %}
            ${{cart.get_total_price}} with {{cart|length}} items
            {% else %}
            :Empty
            {% endif %}
        </div>
        <!-- 장바구니 -->

        <!--제품 목록-->
        {% if item_list %}
        <div class="item-list-container">
            {% for item in item_list %}
            <a href="{% url 'item:item_detail' item.id %}">
                <div class="item-card">
                    <div class="item-image shine">
                        <figure><img src="{{item.item_image.url}}" alt="상품 이미지"></figure>
                    </div>

                    <div class="item-info">
                        <div class="item-category">{{item.item_category}}</div>
                        <h3 class="item-title">{{item.item_title}}</h3>
                        <div class="item-content">{{item.content}}</div>
                        <div class="item-price"><b>{{item.item_price|intcomma }}</b> 원</div>
                        <div class="item-price">
                            <a href="{% url 'item:like_vote' item.id %}">
                                {% if request.user in item.item_likes.all %}
                                <button class="btn-secondary like-review">
                                    <i class="fa fa-heart" aria-hidden="true"></i> Like
                                </button>
                                {% else %}
                                <button class="btn-secondary like-review">
                                    <i class="fa fa-heart" aria-hidden="true"></i> Like
                                </button>

                                {% endif %}
                            </a></div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        {% else %}

        <h1 class="comming">COMMING SOON</h1>

        {% endif %}


        <!-- 페이징 처리 시작-->
        <div class="pagination1">
            <ul class="pagination">
                <!-- 이전 페이지 -->
                {% if item_list.has_previous %}
                <li class="page-item">
                    <button class="prev-btn">
                        <a class="page-link" href="#"
                           data-page="{{ question_list.previous_page_number }}"><</a>
                    </button>
                </li>
                {% else %} <!-- 이전페이가 없으면(마지막이면) -->
                <li class="page-item disabled">
                    <a class="page-link" href="#"></a>
                </li>
                {% endif %}

                <!-- 페이지 리스트-->
                {% for page_number in item_list.paginator.page_range %}
                {% if page_number == item_list.number %}
                <li class="page-item active"> <!--번호 활성화-->
                    <!--                <a class="page-link"-->
                    <!--                   href="?page={{ page_number }}">{{ page_number }}</a>-->
                    <a class="page-link" href="#"
                       data-page="{{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <!--                <a class="page-link"-->
                    <!--                   href="?page={{ page_number }}">{{ page_number }}</a>-->
                    <a class="page-link" href="#"
                       data-page="{{ page_number }}">{{ page_number }}</a>
                    <!-- 해당 경로의 페이지-->
                </li>
                {% endif %}

                {% endfor %}

                <!-- 다음 페이지 -->
                {% if item_list.has_next %}
                <li class="page-item">
                    <!--            <a class="page-link"-->
                    <!--               href="?page={{ question_list.next_page_number }}">다음</a>-->
                    <button class="next-btn">
                        <a class="page-link" href="#"
                           data-page="{{ question_list.next_page_number }}">></a>
                    </button>
                </li>
                {% else %} <!-- 다음페이가 없으면(마지막이면) -->
                <li class="page-item disabled">
                    <a class="page-link" href="#"></a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!-- 페이징 처리 끝 -->

        <!-- 검색 폼 만들기-->
        <form action="" method="get" id="searchForm"> <!-- page, kw get방식으로 요청 -->
            <input type="hidden" name="kw" id="kw">
            <input type="hidden" name="page" id="page">
        </form>

        <!--검색 입력 상자와 찾기버튼-->
        <div class="row justify-content-end mb-2">
            <div class="col-4 input-group">
                <input type="text" class="kw form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button type="button" id="btn_search"
                            class="custom-btn btn_one1">찾기
                    </button>
                </div>
            </div>
        </div>
    </div>

{% include 'footer.html' %}
</section>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        //페이지 처리
        $(".page-link").on('click', function(){   //페이지 번호를 클릭하면
            $("#page").val($(this).data("page")); //해당 페이지 번호를 page 필드에 가져옴
            $("#searchForm").submit();            //폼을 전송
        });

        //검색 처리
        $("#btn_search").on('click', function(){
           let text = $(".kw").val();          //검색어 값
           $("#kw").val(text);                 //폼의 kw 필드에 설정
           $("#page").val(1);                  //1페이지를 page 필드에 설정
           $("#searchForm").submit();          //폼을 전송
        });
    });



</script>

{% endblock %}

templates/item/review_form.html
quit{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <section id="review_form">
        <h4 class="border-bottom pb-2">질문 등록</h4>
        <form action="" method="post">
            {% csrf_token %}
            <!--{{ form.as_p }}--> <!-- input, textarea 태그 포함 -->
            <!-- 유효성 검사 - 오류 처리 시작 -->
            {% if form.errors %}
                <div class="alert alert-danger">
                {% for field in form %}   <!-- 폼을 필드를 순회하면서  -->
                    {% if field.errors %} <!-- 필드에 오류가 있으면 -->
                        {{ field.label }}
                        {{ field.errors }}  <!-- 에러 출력 -->
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
            <!-- 오류 처리 끝-->
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" id="subject" name="subject" class="form-control"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea id="content" name="content" rows="10"
                          class="form-control mb-3">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">등록</button>
        </form>
    </section>
</div>
{% endblock %}